import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { ThoriumGeneratedModule, ThoriumGeneratedSharedModule } from './generated/module.js';
import { ThoriumValidator, registerValidationChecks } from './thorium-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ThoriumAddedServices = {
    validation: {
        ThoriumValidator: ThoriumValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ThoriumServices = LangiumServices & ThoriumAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ThoriumModule: Module<ThoriumServices, PartialLangiumServices & ThoriumAddedServices> = {
    validation: {
        ThoriumValidator: () => new ThoriumValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createThoriumServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Thorium: ThoriumServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ThoriumGeneratedSharedModule
    );
    const Thorium = inject(
        createDefaultModule({ shared }),
        ThoriumGeneratedModule,
        ThoriumModule
    );
    shared.ServiceRegistry.register(Thorium);
    registerValidationChecks(Thorium);
    return { shared, Thorium };
}
